//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Borrower
    {
        public long BorrowID { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public Nullable<decimal> Amont { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Status { get; set; }
        public Nullable<long> CustCode { get; set; }
        public Nullable<decimal> InterestRate { get; set; }
        public Nullable<decimal> Interest { get; set; }
        public Nullable<decimal> Outstanding { get; set; }
        public Nullable<int> PageNo { get; set; }
        public Nullable<decimal> InterstableAmount { get; set; }
        public Nullable<System.DateTime> LastInstallmentDate { get; set; }
    }
}
