//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BuyerProduct
    {
        public long BuyerProductlD { get; set; }
        public string ProductName { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<int> Units { get; set; }
        public string Type { get; set; }
        public Nullable<long> BuyerID { get; set; }
    }
}
