//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Buyer
    {
        public long BuyerID { get; set; }
        public string BuyerName { get; set; }
        public string Address { get; set; }
        public Nullable<decimal> DepositeAmount { get; set; }
        public Nullable<decimal> OutstandingAmount { get; set; }
        public Nullable<System.DateTime> BuyDate { get; set; }
        public byte[] Bill { get; set; }
        public Nullable<long> CustomerCode { get; set; }
        public Nullable<decimal> InterestRate { get; set; }
        public Nullable<decimal> Interest { get; set; }
        public Nullable<System.DateTime> finalDate { get; set; }
        public Nullable<int> PageNo { get; set; }
        public Nullable<decimal> InterstableAmount { get; set; }
        public Nullable<System.DateTime> LastInstallmentDate { get; set; }
    }
}
