//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public long ProductID { get; set; }
        public Nullable<long> CategoryID { get; set; }
        public string ProductName { get; set; }
        public string ProdDesc { get; set; }
        public byte[] Image { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> Unit { get; set; }
        public string Type { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
