//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SellerProduct
    {
        public long SellerProductID { get; set; }
        public string ProductName { get; set; }
        public string Description { get; set; }
        public Nullable<int> Unit { get; set; }
        public Nullable<decimal> weight { get; set; }
        public Nullable<long> SellerID { get; set; }
        public string Type { get; set; }
        public Nullable<long> CategoryID { get; set; }
    }
}
