//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seller
    {
        public long SellerID { get; set; }
        public string SellerName { get; set; }
        public string Address { get; set; }
        public Nullable<decimal> DepositeAmount { get; set; }
        public Nullable<decimal> OutstandingAmount { get; set; }
        public Nullable<System.DateTime> BuyDate { get; set; }
        public string Status { get; set; }
    }
}
